Repository OpenSimulationInterface/osi-visualizer, pull requests merged in 2019-10, with the labels that each got.

#34 Updated osi-visualizer to handle ZMQ Push/Pull configuration in LiME
  include/mainwindow.h
  include/osireader.h
  include/tcpreceiver.h
  src/mainwindow.cpp
  src/mainwindow.ui
  src/osireader.cpp
  src/tcpreceiver.cpp
Labels: feature request

#39 Update Readme and add install script with dependecies
  README.md
  install.sh
Labels: feature request, quality, suggestion

#41 Add local docu
  .travis.yml
  README_docker.md
  doc/_static/images/Connection.png
  doc/_static/images/Demo.png
  doc/_static/images/FieldOfView.png
  doc/_static/images/PlayBack.png
  doc/_static/images/SaveOSIMessage.png
  doc/_static/images/osi_visualizer.png
  doc/howtocontribute.rst
  doc/nvidia-docker.rst
  doc/panels.rst
Labels: documentation, quality
